name: doctest-bug

dependencies:
  - base
  - template-haskell
  - yaml

custom-setup:
  dependencies:
    - base >= 4 && <5
    - Cabal
    - cabal-doctest >= 1 && <1.1

library:
  source-dirs: src

tests:
  doctests:
    main: doctests.hs
    dependencies:
      - base
      - doctest
    source-dirs: src
    other-modules: []
